# Generated by Django 4.2.27 on 2026-01-14 15:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Fund/Investment name', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDERPERFORMING', 'Underperforming'), ('EXITED', 'Exited')], default='ACTIVE', max_length=20)),
                ('sector', models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('HEALTHCARE', 'Healthcare'), ('REAL_ESTATE', 'Real Estate'), ('FINTECH', 'FinTech'), ('AGRICULTURE', 'Agriculture'), ('ENERGY', 'Energy'), ('CONSUMER', 'Consumer'), ('INDUSTRIAL', 'Industrial'), ('OTHER', 'Other')], max_length=20)),
                ('total_invested', models.DecimalField(decimal_places=2, help_text='Total amount invested', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current valuation', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fund_size', models.DecimalField(blank=True, decimal_places=2, help_text='Total fund size (AUM)', max_digits=15, null=True)),
                ('unfunded_commitment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining capital commitment', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('manager', models.CharField(blank=True, help_text='Fund manager name', max_length=255)),
                ('investment_date', models.DateField(help_text='Initial investment date')),
                ('expected_horizon_years', models.IntegerField(blank=True, help_text='Expected investment duration in years', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('fund_vintage', models.IntegerField(blank=True, help_text='Fund vintage year', null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fund deployment progress', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'db_table': 'investments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapitalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('INITIAL_INVESTMENT', 'Initial Investment'), ('CAPITAL_CALL', 'Capital Call'), ('DISTRIBUTION', 'Distribution'), ('PARTIAL_EXIT', 'Partial Exit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount (negative for calls/investments, positive for distributions)', max_digits=15)),
                ('date', models.DateField(help_text='Activity date')),
                ('details', models.TextField(blank=True, help_text='Activity description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_activities', to='investments.investment')),
            ],
            options={
                'verbose_name': 'Capital Activity',
                'verbose_name_plural': 'Capital Activities',
                'db_table': 'capital_activities',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Snapshot date')),
                ('value', models.DecimalField(decimal_places=2, help_text='Investment value at this point in time', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='investments.investment')),
            ],
            options={
                'verbose_name': 'Performance Snapshot',
                'verbose_name_plural': 'Performance Snapshots',
                'db_table': 'performance_snapshots',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['investment', 'date'], name='performance_investm_abcb8b_idx')],
                'unique_together': {('investment', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_dfa5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'sector'], name='investments_user_id_c189ff_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investment_date'], name='investments_investm_235fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalactivity',
            index=models.Index(fields=['investment', 'date'], name='capital_act_investm_644288_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalactivity',
            index=models.Index(fields=['activity_type'], name='capital_act_activit_f8ceb9_idx'),
        ),
    ]
