# Generated by Django 4.2.27 on 2026-01-14 15:43

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(blank=True, help_text='Recipient email (for external recipients)', max_length=254)),
                ('to_name', models.CharField(blank=True, help_text='Recipient name/entity', max_length=255)),
                ('transfer_type', models.CharField(choices=[('FULL', 'Full Transfer'), ('PARTIAL', 'Partial Transfer')], max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of ownership to transfer (for partial transfers)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('transfer_amount', models.DecimalField(decimal_places=2, help_text='Amount being transferred', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transfer fee (2.5%)', max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount recipient receives after fees', max_digits=15)),
                ('reason', models.TextField(help_text='Reason for transfer (required for compliance)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('initiated_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(help_text='User transferring ownership', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_transfers', to='investments.investment')),
                ('to_user', models.ForeignKey(blank=True, help_text='Recipient user (if registered)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ownership Transfer',
                'verbose_name_plural': 'Ownership Transfers',
                'db_table': 'ownership_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RECEIPT', 'Transfer Receipt'), ('AGREEMENT', 'Transfer Agreement'), ('COMPLIANCE', 'Compliance Document'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file', models.FileField(help_text='Document file', upload_to='transfers/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='investments.ownershiptransfer')),
            ],
            options={
                'verbose_name': 'Transfer Document',
                'verbose_name_plural': 'Transfer Documents',
                'db_table': 'transfer_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ownershiptransfer',
            index=models.Index(fields=['from_user', 'status'], name='ownership_t_from_us_ff6742_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershiptransfer',
            index=models.Index(fields=['to_user', 'status'], name='ownership_t_to_user_4febb7_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershiptransfer',
            index=models.Index(fields=['status'], name='ownership_t_status_1e28d8_idx'),
        ),
    ]
