# Generated by Django 4.2.27 on 2026-01-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_ownershiptransfer_transferdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershiptransfer',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Flag to prevent duplicate signal processing'),
        ),
        migrations.AddIndex(
            model_name='ownershiptransfer',
            index=models.Index(fields=['status', 'is_processed'], name='ownership_t_status_e0c35b_idx'),
        ),
    ]
