# Generated by Django 4.2.27 on 2026-02-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('investments', '0003_ownershiptransfer_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='opportunity',
            field=models.ForeignKey(blank=True, help_text='Marketplace opportunity this investment is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='marketplace.marketplaceopportunity'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='name',
            field=models.CharField(blank=True, help_text='Fund/Investment name (deprecated, use opportunity.title)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='sector',
            field=models.CharField(blank=True, choices=[('TECHNOLOGY', 'Technology'), ('HEALTHCARE', 'Healthcare'), ('REAL_ESTATE', 'Real Estate'), ('FINTECH', 'FinTech'), ('AGRICULTURE', 'Agriculture'), ('ENERGY', 'Energy'), ('CONSUMER', 'Consumer'), ('INDUSTRIAL', 'Industrial'), ('OTHER', 'Other')], help_text='Investment sector (deprecated, use opportunity.sector)', max_length=20, null=True),
        ),
    ]
