# Generated by Django 4.2.28 on 2026-02-18 12:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_investment_opportunity_alter_investment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='current_value',
            field=models.DecimalField(decimal_places=2, help_text='Current valuation', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='investment',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, help_text='Total amount invested', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
