# Generated by Django 4.2.28 on 2026-03-02 18:27

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0005_alter_investment_current_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryMarketInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount the buyer wants to acquire (must be ≤ transfer.transfer_amount)', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('interest_date', models.DateField(default=django.utils.timezone.now, help_text='Date of interest / expected settlement date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONVERTED', 'Converted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='The user expressing interest (buyer)', on_delete=django.db.models.deletion.CASCADE, related_name='secondary_market_interests', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(help_text='The secondary-market listing (OwnershipTransfer) the buyer is interested in', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_interests', to='investments.ownershiptransfer')),
            ],
            options={
                'verbose_name': 'Secondary Market Interest',
                'verbose_name_plural': 'Secondary Market Interests',
                'db_table': 'secondary_market_interests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transfer', 'status'], name='secondary_m_transfe_a26d88_idx'), models.Index(fields=['buyer', 'status'], name='secondary_m_buyer_i_6f47e4_idx')],
                'unique_together': {('transfer', 'buyer')},
            },
        ),
    ]
