# Generated by Django 4.2.28 on 2026-03-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_add_secondary_market_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalactivity',
            name='activity_type',
            field=models.CharField(choices=[('INITIAL_INVESTMENT', 'Initial Investment'), ('CAPITAL_CALL', 'Capital Call'), ('DISTRIBUTION', 'Distribution'), ('PARTIAL_EXIT', 'Partial Exit'), ('FULL_EXIT', 'Full Exit')], max_length=20),
        ),
    ]
