# Generated by Django 4.2.28 on 2026-03-04 07:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_add_full_exit_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershiptransfer',
            name='transfer_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transfer fee (0%)', max_digits=15),
        ),
    ]
