# Generated by Django 4.2.27 on 2026-01-14 15:29

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_type', models.CharField(choices=[('BOOKMARKED', 'Bookmarked'), ('REQUESTED_INFO', 'Requested Information'), ('INVESTED', 'Invested')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Investment Interest',
                'verbose_name_plural': 'Investment Interests',
                'db_table': 'investment_interests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Investment opportunity name', max_length=255)),
                ('description', models.TextField(help_text='Short description')),
                ('detailed_description', models.TextField(blank=True, help_text='Full investment memo')),
                ('sector', models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('HEALTHCARE', 'Healthcare'), ('REAL_ESTATE', 'Real Estate'), ('FINTECH', 'FinTech'), ('AGRICULTURE', 'Agriculture'), ('ENERGY', 'Energy'), ('CONSUMER', 'Consumer'), ('INDUSTRIAL', 'Industrial'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('CLOSING_SOON', 'Closing Soon'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('min_investment', models.DecimalField(decimal_places=2, help_text='Minimum investment amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('target_raise_amount', models.DecimalField(decimal_places=2, help_text='Total funding goal', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_raised_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount raised so far', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('target_irr', models.DecimalField(blank=True, decimal_places=2, help_text='Target IRR percentage', max_digits=5, null=True)),
                ('investment_term_years', models.IntegerField(blank=True, help_text='Investment duration in years', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('investment_type', models.CharField(choices=[('FIXED', 'Fixed Investment'), ('VARIABLE', 'Variable Investment')], default='FIXED', max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('payout_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], default='ANNUALLY', max_length=20)),
                ('currency', models.CharField(default='NGN', help_text='Currency code', max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Star rating (0-5)', max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('investors_count', models.IntegerField(default=0, help_text='Number of investors')),
                ('platform_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Platform rating score', max_digits=3, null=True)),
                ('verification_type', models.CharField(choices=[('VERIFIED', 'Verified'), ('PENDING', 'Pending'), ('UNVERIFIED', 'Unverified')], default='PENDING', max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('run_rate_sales_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum run rate sales', max_digits=15, null=True)),
                ('run_rate_sales_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum run rate sales', max_digits=15, null=True)),
                ('investment_requirements', models.TextField(blank=True, help_text='Investment criteria/requirements')),
                ('disclaimer', models.TextField(blank=True, help_text='Legal disclaimer')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured opportunity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketplace Opportunity',
                'verbose_name_plural': 'Marketplace Opportunities',
                'db_table': 'marketplace_opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text='Tag text', max_length=100)),
                ('tag_type', models.CharField(choices=[('INDUSTRY', 'Industry'), ('FEATURE', 'Feature'), ('STATUS', 'Status'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='marketplace.marketplaceopportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Tag',
                'verbose_name_plural': 'Opportunity Tags',
                'db_table': 'opportunity_tags',
            },
        ),
        migrations.CreateModel(
            name='OpportunityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document name', max_length=255)),
                ('file', models.FileField(help_text='Document file', upload_to='marketplace/documents/')),
                ('document_type', models.CharField(choices=[('MEMO', 'Investment Memo'), ('RATING', 'DataPro Rating'), ('PROSPECTUS', 'Prospectus'), ('FINANCIAL', 'Financial Statement'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='marketplace.marketplaceopportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Document',
                'verbose_name_plural': 'Opportunity Documents',
                'db_table': 'opportunity_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceopportunity',
            index=models.Index(fields=['status', 'sector'], name='marketplace_status_e05645_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceopportunity',
            index=models.Index(fields=['is_featured'], name='marketplace_is_feat_d8a515_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceopportunity',
            index=models.Index(fields=['-created_at'], name='marketplace_created_5fcb1e_idx'),
        ),
        migrations.AddField(
            model_name='investmentinterest',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='marketplace.marketplaceopportunity'),
        ),
        migrations.AddField(
            model_name='investmentinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='opportunitytag',
            unique_together={('opportunity', 'tag_name')},
        ),
        migrations.AddIndex(
            model_name='investmentinterest',
            index=models.Index(fields=['user', 'interest_type'], name='investment__user_id_baf0fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='investmentinterest',
            unique_together={('user', 'opportunity', 'interest_type')},
        ),
    ]
