# Generated by Django 4.2.27 on 2026-02-14 08:21

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expected investment amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('investment_date', models.DateField(help_text='Expected date of investment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_interest_pledges', to='marketplace.marketplaceopportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_interest_pledges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor Interest',
                'verbose_name_plural': 'Investor Interests',
                'db_table': 'investor_interests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='investor_in_user_id_50cf12_idx'), models.Index(fields=['opportunity'], name='investor_in_opportu_945871_idx')],
            },
        ),
    ]
