# Generated by Django 4.2.27 on 2026-02-14 09:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_investorinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplaceopportunity',
            name='run_rate_sales_max',
        ),
        migrations.RemoveField(
            model_name='marketplaceopportunity',
            name='run_rate_sales_min',
        ),
        migrations.AddField(
            model_name='marketplaceopportunity',
            name='cash_runway',
            field=models.CharField(blank=True, help_text="Estimated cash runway (e.g., '18+ months')", max_length=100),
        ),
        migrations.AddField(
            model_name='marketplaceopportunity',
            name='current_capacity',
            field=models.CharField(blank=True, help_text="Current operational capacity (e.g., '500 clients per month')", max_length=255),
        ),
        migrations.AddField(
            model_name='marketplaceopportunity',
            name='growth_capacity',
            field=models.CharField(blank=True, help_text='Potential growth capacity with existing infrastructure', max_length=255),
        ),
        migrations.AddField(
            model_name='marketplaceopportunity',
            name='leadership_experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Combined years of leadership experience', null=True),
        ),
        migrations.AddField(
            model_name='marketplaceopportunity',
            name='monthly_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average monthly revenue in Naira', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceopportunity',
            name='net_cash_flow',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly net cash flow in Naira', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceopportunity',
            name='operating_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average operating expenses in Naira', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceopportunity',
            name='staff_departments',
            field=models.TextField(blank=True, help_text='Breakdown of staff departments'),
        ),
        migrations.AddField(
            model_name='marketplaceopportunity',
            name='total_staff_count',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of staff', null=True),
        ),
        migrations.AddField(
            model_name='marketplaceopportunity',
            name='utilization_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current utilization rate as a percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))]),
        ),
    ]
