# Generated by Django 4.2.27 on 2026-02-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_marketplaceopportunity_run_rate_sales_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorinterest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONVERTED', 'Converted to Investment'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Whether this interest has been registered as an actual investment', max_length=20),
        ),
        migrations.AddIndex(
            model_name='investorinterest',
            index=models.Index(fields=['status'], name='investor_in_status_06b30f_idx'),
        ),
    ]
