# Generated by Django 4.2.27 on 2026-01-14 18:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='investment_preferences',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred sectors'),
        ),
        migrations.AddField(
            model_name='user',
            name='investor_type',
            field=models.CharField(blank=True, choices=[('ACCREDITED', 'Accredited Investor'), ('QUALIFIED', 'Qualified Purchaser'), ('INSTITUTIONAL', 'Institutional Investor')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Premium investor verification status'),
        ),
        migrations.AddField(
            model_name='user',
            name='member_since',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 1, 14, 18, 7, 21, 47421, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_tolerance',
            field=models.CharField(blank=True, choices=[('CONSERVATIVE', 'Conservative'), ('MODERATE', 'Moderate'), ('AGGRESSIVE', 'Aggressive'), ('MODERATE_TO_AGGRESSIVE', 'Moderate to Aggressive')], max_length=30),
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_updates', models.BooleanField(default=True, help_text='Quarterly valuations and performance reports')),
                ('transfer_notifications', models.BooleanField(default=True, help_text='Updates on ownership transfers')),
                ('market_opportunities', models.BooleanField(default=False, help_text='New investment opportunities')),
                ('distribution_notices', models.BooleanField(default=True, help_text='Cash distributions and dividend payments')),
                ('security_alerts', models.BooleanField(default=True, help_text='Login attempts and security activities')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'user_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('LEGAL', 'Legal'), ('REPORT', 'Report'), ('TAX', 'Tax'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='user_documents/')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('NEW', 'New'), ('REQUIRED', 'Required')], default='NEW', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Document',
                'verbose_name_plural': 'User Documents',
                'db_table': 'user_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text='Device identifier (e.g., MacBook Pro)', max_length=255)),
                ('location', models.CharField(help_text='Location (e.g., New York, NY)', max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', '-last_activity'], name='user_sessio_user_id_3a59ae_idx'), models.Index(fields=['session_key'], name='user_sessio_session_cc84b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('PROFILE_UPDATE', 'Profile Updated'), ('PASSWORD_CHANGE', 'Password Changed'), ('TRANSFER_INITIATED', 'Transfer Initiated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PORTFOLIO_UPDATE', 'Portfolio Value Updated'), ('2FA_ENABLED', 'Two-Factor Authentication Enabled'), ('2FA_DISABLED', 'Two-Factor Authentication Disabled')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_activi_user_id_47a698_idx'), models.Index(fields=['activity_type'], name='user_activi_activit_534635_idx')],
            },
        ),
    ]
