# Generated by Django 4.2.27 on 2026-01-14 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Public display name', max_length=255)),
                ('investor_category', models.CharField(choices=[('FAMILY_OFFICE', 'Family Office'), ('ANGEL', 'Angel Investor'), ('VC', 'Venture Capital'), ('PE', 'Private Equity'), ('INSTITUTIONAL', 'Institutional Investor'), ('INDIVIDUAL', 'Individual Investor')], max_length=20)),
                ('bio', models.TextField(blank=True, help_text='About the investor')),
                ('investment_philosophy', models.TextField(blank=True)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_country', models.CharField(blank=True, max_length=100)),
                ('min_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('preferred_sectors', models.JSONField(blank=True, default=list, help_text='List of preferred sectors')),
                ('preferred_stages', models.JSONField(blank=True, default=list, help_text='Seed, Series A, B, etc.')),
                ('risk_profile', models.CharField(blank=True, choices=[('CONSERVATIVE', 'Conservative'), ('BALANCED', 'Balanced'), ('GROWTH_FOCUSED', 'Growth-focused'), ('AGGRESSIVE', 'Aggressive')], max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Show in investor directory')),
                ('is_accepting_connections', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor Profile',
                'verbose_name_plural': 'Investor Profiles',
                'db_table': 'investor_profiles',
                'indexes': [models.Index(fields=['is_public', 'is_accepting_connections'], name='investor_pr_is_publ_ce7463_idx'), models.Index(fields=['location_country', 'location_city'], name='investor_pr_locatio_284833_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvestorConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Connection request message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL)),
                ('to_investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor Connection',
                'verbose_name_plural': 'Investor Connections',
                'db_table': 'investor_connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_investor', 'status'], name='investor_co_from_in_7f2dc7_idx'), models.Index(fields=['to_investor', 'status'], name='investor_co_to_inve_02df12_idx')],
                'unique_together': {('from_investor', 'to_investor')},
            },
        ),
    ]
