# Generated by Django 4.2.28 on 2026-03-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_investorprofile_investorconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='investor_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual Investor'), ('INSTITUTIONAL', 'Institutional Investor'), ('COLLECTIVE', 'Collective Investor')], max_length=20),
        ),
    ]
