# Generated by Django 4.2.28 on 2026-03-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_investor_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='investor_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual Investor'), ('INSTITUTIONAL', 'Institutional Investor'), ('COLLECTIVE', 'Collective Investor'), ('QUALIFIED', 'Qualified Investor'), ('RETAIL', 'Retail Investor')], max_length=20),
        ),
    ]
