# Generated by Django 4.2.28 on 2026-03-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_qualified_retail_investor_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='investor_type',
            field=models.CharField(blank=True, choices=[('INSTITUTIONAL', 'Institutional Investor'), ('COLLECTIVE', 'Collective Investor'), ('QUALIFIED', 'Qualified Investor'), ('RETAIL', 'Retail Investor')], max_length=20),
        ),
    ]
